
export const order = [

	/* order */
	
	{name:"accountEmail", input:"{{order.accountEmail}}", output:"hello@insphire.com", example:"Return order account email", status:false,  module:"order"},
	{name:"accountName", input:"{{order.accountName}}", output:"inspHire Ltd", example:"Return order account name ", status:false, module:"order"},
	{name:"billingAddressString", input:"{{order.billingAddressString}}", output:"inspHire Ltd, Unit 5, Chase Park, Daleside Road, Nottingham, Nottinghamshire, United Kingdom, NG2 4GT", example:"Return order full billing address", status:false, module:"order"},
	{name:"billingPlaceName", input:"{{order.billingPlaceName}}", output:"inspHire Ltd", example:"Return order billing place name ", status:false, module:"order"},
	{name:"chargingEndDate", input:"{{order.chargingEndDate}}", output:"2023-12-17T17:00:00Z", example:"Return order charging end date ", status:false,  module:"order"},
	{name:"chargingStartDate", input:"{{order.chargingStartDate}}", output:"2023-12-13T09:00:00Z", example:"Return order charging start date", status:false,  module:"order"},
	{name:"collectionAddressString", input:"{{order.collectionAddressString}}", output:"99,  Street, Nottingham, England, United Kingdom, NG9 9FD", example:"Return order full collection address ", status:false,  module:"order"},
	{name:"collectionPlaceName", input:"{{order.collectionPlaceName}}", output:"House", example:"Return order collection place name ", status:false,  module:"order"},
	{name:"contactName", input:"{{order.contactName}}", output:"John Cash", example:"Return order contact name ", status:false,  module:"order"},
	{name:"createDate", input:"{{order.createDate}}", output:"2023-12-13T14:58:16.296297Z", example:"Return order create date ", status:false,  module:"order"},
	{name:"currencySymbol", input:"{{order.currencySymbol}}", output:"£", example:"Return order currency symbol ", status:false,  module:"order"},
	{name:"customerReference", input:"{{order.customerReference}}", output:"Customer Ref: 1234", example:"Return order customer ref  ", status:false,  module:"order"},
	{name:"deliveryAddressString", input:"{{order.deliveryAddressString}}", output:"99,  Street, Nottingham, England, United Kingdom, NG9 9FD", example:"Return order full delivery address ", status:false,  module:"order"},
	{name:"deliveryPlaceName", input:"{{order.deliveryPlaceName}}", output:"House", example:"Return order delivery place name ", status:false,  module:"order"},
	{name:"depotName", input:"{{order.depotName}}", output:"Alan Store", example:"Return order depot name ", status:false, module:"order"},
	{name:"documentNumber", input:"{{order.documentNumber}}", output:"12 - ORD:GB/ALA", example:"Return order doc number ", status:false,  module:"order"},
	{name:"endDate", input:"{{order.endDate}}", output:"1753-01-01T00:00:00Z", example:"Return order end date ", status:false,  module:"order"},
	{name:"invoiceRunCodeRef", input:"{{order.invoiceRunCodeRef}}", output:"00000000-0000-0000-0000-000000000000", example:"Return order invoice run code ref ", status:false,  module:"order"},
	{name:"invoicedFlag", input:"{{order.invoicedFlag}}", output:"true/false ", example:"Return whether order was invoiced or not ", status:false,  module:"order"},
	{name:"invoicedUptoDate", input:"{{order.invoicedUptoDate}}", output:"2023-12-14T23:59:00Z", example:"Return order invoiced up to ", status:false,  module:"order"},
	{name:"noOfItems", input:"{{order.noOfItems}}", output:1, example:"Return order number of items ", status:false, module:"order"},
	{name:"openEndedFlag", input:"{{order.openEndedFlag}}", output:"true/false ", example:"Return whether order is open ended or not  ", status:false,  module:"order"},
	{name:"orderDate", input:"{{order.orderDate}}", output:"2023-12-13T14:45:00Z", example:"Return order date ", status:false,  module:"order"},
	{name:"orderedBy", input:"{{order.orderedBy}}", output:"John Cash", example:"Return order ordered by who ", status:false,  module:"order"},
	{name:"ownerUserEmail", input:"{{order.ownerUserEmail}}", output:"alan.da.silva.souza@current-rms.com", example:"Return order owner email ", status:false,  module:"order"},
	{name:"ownerUserFullName", input:"{{order.ownerUserFullName}}", output:"Alan Souza", example:"Return order owner name ", status:false,  module:"order"},
	{name:"paymentTermName", input:"{{order.paymentTermName}}", output:"30 Days", example:"Return order payment term ", status:false,  module:"order"},
	{name:"projectName", input:"{{order.projectName}}", output:"Project Big", example:"Return order project name ", status:false,  module:"order"},
	{name:"rentalLength", input:"{{order.rentalLength}}", output:5, example:"Return order time period ", status:false, module:"order"},
	{name:"salesPerson", input:"{{order.salesPerson}}", output:"Will Smith", example:"Return order sales person ", status:false,  module:"order"},
	{name:"startDate", input:"{{order.startDate}}", output:"2023-12-13T09:00:00Z", example:"Return order start date ", status:false,  module:"order"},
	{name:"state", input:"{{order.state}}", output:"Order", example:"Return order state", status:false, module:"order"},
	{name:"status", input:"{{order.status}}", output:"Active", example:"Return order status ", status:false,  module:"order"},
	{name:"supplierTotalCharge", input:"{{order.supplierTotalCharge}}", output:0, example:"Return order supplier total charge without tax", status:false, module:"order"},
	{name:"supplierTotalChargeIncludingTax", input:"{{order.supplierTotalChargeIncludingTax}}", output:0, example:"Return order supplier total charge inc tax ", status:false,  module:"order"},
	{name:"supplierTotalTax", input:"{{order.supplierTotalTax}}", output:0, example:"Return order supplier total tax ", status:false,  module:"order"},
	{name:"timeZone", input:"{{order.timeZone}}", output:"Europe/London", example:"Return order time zone ", status:false,  module:"order"},
	{name:"timeZoneName", input:"{{order.timeZoneName}}", output:"(+00:00) Europe/London", example:"Return order time zone name ", status:false,  module:"order"},
	{name:"totalCharge", input:"{{order.totalCharge}}", output:20, example:"Return order total charge without tax", status:false, module:"order"},
	{name:"totalChargeIncludingTax", input:"{{order.totalChargeIncludingTax}}", output:24, example:"Return order total charge inc tax ", status:false,  module:"order"},
	{name:"totalInvoiced", input:"{{order.totalInvoiced}}", output:12, example:"Return order total invoiced ", status:false,  module:"order"},
	{name:"totalRental", input:"{{order.totalRental}}", output:20, example:"Return order  total rental", status:false,  module:"order"},
	{name:"totalSale", input:"{{order.totalSale}}", output:0, example:"Return order total sale ", status:false,  module:"order"},
	{name:"totalService", input:"{{order.totalService}}", output:0, example:"Return order total service ", status:false,  module:"order"},
	{name:"totalSurcharge", input:"{{order.totalSurcharge}}", output:0, example:"Return order total surcharge ", status:false,  module:"order"},
	{name:"totalTax", input:"{{order.totalTax}}", output:4, example:"Return order total tax ", status:false,  module:"order"},
	{name:"totalWeight", input:"{{order.totalWeight}}", output:30, example:"Return order total weight ", status:false,  module:"order"},
	{name:"weightUnitSymbol", input:"{{order.weightUnitSymbol}}", output:"kg", example:"Return order total weight unit ", status:false, module:"order"},

	/* order.orderBillingPlace */
	
	{name:"address1", input:"{{order.orderBillingPlace.address1}}", output:"inspHire Ltd", example:"Return order billing place address", status:false, module:"orderBillingPlace" },
	{name:"address2", input:"{{order.orderBillingPlace.address2}}", output:"Unit 5, Chase Park, Daleside Road", example:"Return order billing place address", status:false, module:"orderBillingPlace"  },
	{name:"city", input:"{{order.orderBillingPlace.city}}", output:"Nottingham", example:"Return order billing place city", status:false, module:"orderBillingPlace"  },
	{name:"countryIso", input:"{{order.orderBillingPlace.countryIso}}", output:"GB", example:"Return order billing place country symbol", status:false, module:"orderBillingPlace"  },
	{name:"countryName", input:"{{order.orderBillingPlace.countryName}}", output:"United Kingdom", example:"Return order billing place name", status:false, module:"orderBillingPlace"  },
	{name:"county", input:"{{order.orderBillingPlace.county}}", output:"Nottinghamshire", example:"Return order billing place county", status:false, module:"orderBillingPlace"  },
	{name:"email", input:"{{order.orderBillingPlace.email}}", output:"hello@insphire.com", example:"Return order billing place email", status:false, module: "orderBillingPlace" },
	{name:"fax", input:"{{order.orderBillingPlace.fax}}", output:"example.com", example:"Return order billing place fax", status:false, module:"orderBillingPlace" },
	{name:"name", input:"{{order.orderBillingPlace.name}}", output:"inspHire Ltd", example:"Return order billing place name", status:false, module: "orderBillingPlace" },
	{name:"postcode", input:"{{order.orderBillingPlace.postcode}}", output:"NG2 4GT", example:"Return order billing place postcode", status:false, module:"orderBillingPlace"  },
	{name:"telephone", input:"{{order.orderBillingPlace.telephone}}", output:"0115 979 3377", example:"Return order billing place telephone", status:false, module: "orderBillingPlace" },
	{name:"type", input:"{{order.orderBillingPlace.type}}", output:"Head Office", example:"Return order billing place type", status:false, module:"orderBillingPlace"  },
	{name:"website", input:"{{order.orderBillingPlace.website}}", output:"www.inspHire.com", example:"Return order billing place website", status:false, module:"orderBillingPlace"  },

	/*  order.orderCollectionAddress */
	
	{name:"address1", input:"{{order.orderCollectionAddress.address1}}", output:"99, Brightmoor Street", example:"Return order collection address ", status:false, module:"orderCollectionAddress" },
	{name:"address2", input:"{{order.orderCollectionAddress.address2}}", output:"", example:"Return order collection address ", status:false, module:"orderCollectionAddress" },
	{name:"city", input:"{{order.orderCollectionAddress.city}}", output:"Nottingham", example:"Return order collection address city", status:false, module: "orderCollectionAddress"},
	{name:"countryIso", input:"{{order.orderCollectionAddress.countryIso}}", output:"GB", example:"Return order collection address country initials", status:false, module:"orderCollectionAddress" },
	{name:"countryName", input:"{{order.orderCollectionAddress.countryName}}", output:"United Kingdom", example:"Return order collection address country", status:false, module:"orderCollectionAddress" },
	{name:"county", input:"{{order.orderCollectionAddress.county}}", output:"England", example:"Return order collection address county ", status:false, module:"orderCollectionAddress" },
	{name:"postcode", input:"{{order.orderCollectionAddress.postcode}}", output:"NG9 9FD", example:"Return order collection address postcode ", status:false, module: "orderCollectionAddress"},

	/* order.orderCollectionPlace */
	
	{name:"activeFlag", input:"{{order.orderCollectionPlace.activeFlag}}", output:"true/false ", example:"Return whether or not order collection place is active", status:false, module:"orderCollectionPlace" },
	{name:"address1", input:"{{order.orderCollectionPlace.address1}}", output:"99, Brightmoor Street", example:"Return order collection place address", status:false, module:"orderCollectionPlace" },
	{name:"address2", input:"{{order.orderCollectionPlace.address2}}", output:"", example:"Return order collection place address", status:false, module:"orderCollectionPlace" },
	{name:"city", input:"{{order.orderCollectionPlace.city}}", output:"Nottingham", example:"Return order collection place city", status:false, module:"orderCollectionPlace" },
	{name:"countryIso", input:"{{order.orderCollectionPlace.countryIso}}", output:"GB", example:"Return order collection place country", status:false, module:"orderCollectionPlace" },
	{name:"countryName", input:"{{order.orderCollectionPlace.countryName}}", output:"United Kingdom", example:"Return order collection place country", status:false, module:"orderCollectionPlace" },
	{name:"county", input:"{{order.orderCollectionPlace.county}}", output:"England", example:"Return order collection place county", status:false, module: "orderCollectionPlace"},
	{name:"email", input:"{{order.orderCollectionPlace.email}}", output:"alansouzauk@gmail.com", example:"Return order collection place email", status:false, module:"orderCollectionPlace" },
	{name:"fax", input:"{{order.orderCollectionPlace.fax}}", output:"12345", example:"Return order collection place fax", status:false, module:"orderCollectionPlace" },
	{name:"fileLink", input:"{{order.orderCollectionPlace.fileLink}}", output:"https://europa-dev.s3.eu-west-1.amazonaws.com/logo", example:"Return order collection place file attached", status:false, module: "orderCollectionPlace"},
	{name:"name", input:"{{order.orderCollectionPlace.name}}", output:"House", example:"Return order collection place name", status:false, module:"orderCollectionPlace" },
	{name:"postcode", input:"{{order.orderCollectionPlace.postcode}}", output:"NG9 9FD", example:"Return order collection place postcode", status:false, module:"orderCollectionPlace" },
	{name:"telephone", input:"{{order.orderCollectionPlace.telephone}}", output:"9999999", example:"Return order collection place telephone", status:false, module: "orderCollectionPlace"},
	{name:"thumbLink", input:"{{order.orderCollectionPlace.thumbLink}}", output:"https://europa-dev.s3.eu-west-1.amazonaws.com/logo", example:"Return order collection place logo", status:false, module: "orderCollectionPlace"},
	{name:"type", input:"{{order.orderCollectionPlace.type}}", output:"Head Office", example:"Return order collection place type", status:false, module:"orderCollectionPlace" },
	{name:"website", input:"{{order.orderCollectionPlace.website}}", output:"www.alansouzauk.com", example:"Return order collection place website", status:false, module:"orderCollectionPlace" },

	/* order.orderDeliveryPlace */

	{name:"address1", input:"{{order.orderDeliveryPlace.address1}}", output:"inspHire Ltd", example:"Return order delivery place address", status:false, module:"orderDeliveryPlace" },
	{name:"address2", input:"{{order.orderDeliveryPlacee.address2}}", output:"Unit 5, Chase Park, Daleside Road", example:"Return order delivery place address", status:false, module:"orderDeliveryPlace" },
	{name:"city", input:"{{order.orderDeliveryPlace.city}}", output:"Nottingham", example:"Return order delivery place city", status:false, module: "orderDeliveryPlace"},
	{name:"countryIso", input:"{{order.orderDeliveryPlace.countryIso}}", output:"GB", example:"Return order delivery place country symbol", status:false, module: "orderDeliveryPlace"},
	{name:"countryName", input:"{{order.orderDeliveryPlace.countryName}}", output:"United Kingdom", example:"Return order delivery place name", status:false, module:"orderDeliveryPlace" },
	{name:"county", input:"{{order.orderDeliveryPlace.county}}", output:"Nottinghamshire", example:"Return order delivery place county", status:false, module:"orderDeliveryPlace" },
	{name:"email", input:"{{order.orderDeliveryPlace.email}}", output:"hello@insphire.com", example:"Return order delivery place email", status:false, module:"orderDeliveryPlace" },
	{name:"fax", input:"{{order.orderDeliveryPlace.fax}}", output:"example.com", example:"Return order delivery place fax", status:false, module:"orderDeliveryPlace" },
	{name:"name", input:"{{order.orderDeliveryPlace.name}}", output:"inspHire Ltd", example:"Return order delivery place name", status:false, module:"orderDeliveryPlace" },
	{name:"postcode", input:"{{order.orderDeliveryPlace.postcode}}", output:"NG2 4GT", example:"Return order delivery place postcode", status:false, module: "orderDeliveryPlace"},
	{name:"telephone", input:"{{order.orderDeliveryPlace.telephone}}", output:"0115 979 3377", example:"Return order delivery place telephone", status:false, module: "orderDeliveryPlace"},
	{name:"type", input:"{{order.orderDeliveryPlace.type}}", output:"Head Office", example:"Return order delivery place type", status:false, module:"orderDeliveryPlace" },
	{name:"website", input:"{{order.orderDeliveryPlace.website}}", output:"www.inspHire.com", example:"Return order delivery place website", status:false, module: "orderDeliveryPlace"},
    {name:"fileLink", input:"{{order.orderDeliveryPlace.fileLink}}", output:"https://europa-dev.s3.eu-west-1.amazonaws.com/logo", example:"Return order delivery place file attached", status:false, module: "orderDeliveryPlace"},
	{name:"thumbLink", input:"{{order.orderDeliveryPlace.thumbLink}}", output:"https://europa-dev.s3.eu-west-1.amazonaws.com/logo", example:"Return order delivery place logo", status:false, module:"orderDeliveryPlace" },

	/*  order.orderDeliveryAddress */

	{name:"address1", input:"{{order.orderDeliveryAddress.address1}}", output:"99, Brightmoor Street", example:"Return order delivery address ", status:false, module: "orderDeliveryAddress"},
	{name:"address2", input:"{{order.orderDeliveryAddress.address2}}", output:"", example:"Return order delivery address ", status:false, module: "orderDeliveryAddress"},
	{name:"city", input:"{{order.orderDeliveryAddress.city}}", output:"Nottingham", example:"Return order delivery address city", status:false, module: "orderDeliveryAddress"},
	{name:"countryIso", input:"{{order.orderDeliveryAddress.countryIso}}", output:"GB", example:"Return order delivery address country initials", status:false, module: "orderDeliveryAddress"},
	{name:"countryName", input:"{{order.orderDeliveryAddress.countryName}}", output:"United Kingdom", example:"Return order delivery address country", status:false, module: "orderDeliveryAddress"},
	{name:"county", input:"{{order.orderDeliveryAddress.county}}", output:"England", example:"Return order delivery address county ", status:false, module:"orderDeliveryAddress" },
	{name:"postcode", input:"{{order.orderDeliveryAddress.postcode}}", output:"NG9 9FD", example:"Return order delivery address postcode ", status:false, module:"orderDeliveryAddress" },

	/* LOOP order.rentalOrderItems */

	{name:"bookInDate", input:"{{item.bookInDate}}", output:"", example:"Return item book in date", status:false, module:"order.rentalOrderItems"},
	{name:"bookInDescription", input:"{{item.bookInDescription}}", output:"", example:"Return item book in description", status:false, module:"order.rentalOrderItems"},
	{name:"chargingEndDate", input:"{{item.chargingEndDate}}", output:"2023-12-17T17:00:00Z", example:"Return item charge end date", status:false, module:"order.rentalOrderItems"},
	{name:"chargingStartDate", input:"{{item.chargingStartDate}}", output:"2023-12-14T09:36:00Z", example:"Return item charge start date", status:false, module:"order.rentalOrderItems"},
	{name:"currencySymbol", input:"{{item.currencySymbol}}", output:"£", example:"Return item currency symbol", status:false, module:"order.rentalOrderItems"},
	{name:"currentItemName", input:"{{item.currentItemName}}", output:"6\" Bucket", example:"Return item name", status:false, module:"order.rentalOrderItems"},
	{name:"description", input:"{{item.description}}", output:"note description", example:"Return item note description", status:false, module:"order.rentalOrderItems"},
	{name:"discount", input:"{{item.discount}}", output:0, example:"Return item discount", status:false, module:"order.rentalOrderItems"},
	{name:"discountableFlag", input:"{{item.discountableFlag}}", output:"true/false", example:"Return whether or not the item has a discount", status:false, module:"order.rentalOrderItems"},
	{name:"id", input:"{{item.id}}", output:"16d43ce0-2153-4aa0-92d7-051521cf4d95", example:"Return the item id", status:false, module:"order.rentalOrderItems"},
	{name:"index", input:"{{item.index}}", output:0, example:"Return item index position in the array", status:false, module:"order.rentalOrderItems"},
	{name:"invoiceAtOffRentOnlyFlag", input:"{{item.invoiceAtOffRentOnlyFlag}}", output:"true/false", example:"Return whether or not the item is invoiced after returned", status:false, module:"order.rentalOrderItems"},
	{name:"itemName", input:"{{item.itemName}}", output:"6\" Bucket", example:"Return item name", status:false, module:"order.rentalOrderItems"},
	{name:"level", input:"{{item.level}}", output:0, example:"Return item level - accessory 1 and subsequently ", status:false, module:"order.rentalOrderItems"},
	{name:"minimumHirePeriodAppliedFlag", input:"{{item.minimumHirePeriodAppliedFlag}}", output:"true/false", example:"Return whether or not the item has a minimum rental period", status:false, module:"order.rentalOrderItems"},
	{name:"price", input:"{{item.price}}", output:10, example:"Return item price", status:false, module:"order.rentalOrderItems"},
	{name:"quantity", input:"{{item.quantity}}", output:1, example:"Return item quantity", status:false, module:"order.rentalOrderItems"},
	{name:"quantityDamaged", input:"{{item.quantityDamaged}}", output:0, example:"Return item quantity damaged ", status:false, module:"order.rentalOrderItems"},
	{name:"quantityLost", input:"{{item.quantityLost}}", output:0, example:"Return item quantity lost ", status:false, module:"order.rentalOrderItems"},
	{name:"quantityOK", input:"{{item.quantityOK}}", output:0, example:"Return item quantity OK ", status:false, module:"order.rentalOrderItems"},
	{name:"quantityReturnRequested", input:"{{item.quantityReturnRequested}}", output:0, example:"Return item quantity return request ", status:false, module:"order.rentalOrderItems"},
	{name:"quantityReturned", input:"{{item.quantityReturned}}", output:0, example:"Return item quantity returned ", status:false, module:"order.rentalOrderItems"},
	{name:"quantitySold", input:"{{item.quantitySold}}", output:0, example:"Return item quantity sold ", status:false, module:"order.rentalOrderItems"},
	{name:"rateDefinitionLeadingRateType", input:"{{item.rateDefinitionLeadingRateType}}", output:0, example:"", status:false, module:"order.rentalOrderItems"},
	{name:"rateDefinitionName", input:"{{item.rateDefinitionName}}", output:"Daily Rate", example:"Return item rate name", status:false, module:"order.rentalOrderItems"},
	{name:"rateDefinitionRateType", input:"{{item.rateDefinitionRateType}}", output:0, example:"Return item rate type ", status:false, module:"order.rentalOrderItems"},
	{name:"revenueGroupName", input:"{{item.revenueGroupName}}", output:"Rental Revenue", example:"Return item revenue group ", status:false, module:"order.rentalOrderItems"},
	{name:"shortageFlag", input:"{{item.shortageFlag}}", output:"true/false", example:"Return whether or not the item has a shortage ", status:false, module:"order.rentalOrderItems"},
	{name:"status", input:"{{item.status}}", output:"On Rent", example:"Return item status ", status:false, module:"order.rentalOrderItems"},
	{name:"stockLevelItemNumber", input:"{{item.stockLevelItemNumber}}", output:"BUCK001", example:"Return item stock number ", status:false, module:"order.rentalOrderItems"},
	{name:"subRentFlag", input:"{{item.subRentFlag}}", output:"true/false", example:"Return whether or not the item is sub-rented ", status:false, module:"order.rentalOrderItems"},
	{name:"substitutedFlag", input:"{{item.substitutedFlag}}", output:"true/false", example:"Return whether or not the item has been substituted", status:false, module:"order.rentalOrderItems"},
	{name:"supplierDiscount", input:"{{item.supplierDiscount}}", output:0, example:"Return item supplier discount", status:false, module:"order.rentalOrderItems"},
	{name:"supplierPrice", input:"{{item.supplierPrice}}", output:0, example:"Return item supplier price", status:false, module:"order.rentalOrderItems"},
	{name:"supplierTotalCharge", input:"{{item.supplierTotalCharge}}", output:0, example:"Return item supplier total charge", status:false, module:"order.rentalOrderItems"},
	{name:"supplierTotalTax", input:"{{item.supplierTotalTax}}", output:0, example:"Return item supplier total tax", status:false, module:"order.rentalOrderItems"},
	{name:"taxClassName", input:"{{item.taxClassName}}", output:"Standard VAT", example:"Return item tax class name", status:false, module:"order.rentalOrderItems"},
	{name:"thumbLink", input:"{{item.thumbLink}}", output:"https://europa-dev.s3.eu-west-1.amazonaws.com/image", example:"Return item image", status:false, module:"order.rentalOrderItems"},
	{name:"totalCharge", input:"{{item.totalCharge}}", output:20, example:"Return item total charge", status:false, module:"order.rentalOrderItems"},
	{name:"totalDays", input:"{{item.totalDays}}", output:2, example:"Return item total days on order", status:false, module:"order.rentalOrderItems"},
	{name:"totalMonths", input:"{{item.totalMonths}}", output:1, example:"Return item total months", status:false, module:"order.rentalOrderItems"},
	{name:"totalSurcharge", input:"{{item.totalSurcharge}}", output:0, example:"Return item total surcharge", status:false, module:"order.rentalOrderItems"},
	{name:"totalTax", input:"{{item.totalTax}}", output:4, example:"Return item total tax", status:false, module:"order.rentalOrderItems"},
	{name:"totalWeekends", input:"{{item.totalWeekends}}", output:1, example:"Return item total weekends", status:false, module:"order.rentalOrderItems"},
	{name:"totalWeeks", input:"{{item.totalWeeks}}", output:1, example:"Return item total weeks", status:false, module:"order.rentalOrderItems"},
	{name:"useBookInDateFlag", input:"{{item.useBookInDateFlag}}", output:"true/false", example:"Return whether or not you are using the book in date to charge", status:false, module:"order.rentalOrderItems"},
	{name:"zeroPricedFlag", input:"{{item.zeroPricedFlag}}", output:"true/false", example:"Return whether or not the item is zero priced ", status:false, module:"order.rentalOrderItems"},
	{name:"day1", input:"{{item.rate.day1}}", output:75, example:" ", status:false, module:"order.rentalOrderItems"},
	{name:"day1Flag", input:"{{item.rate.day1Flag}}", output:"true/false", example:" ", status:false, module:"order.rentalOrderItems"},
	{name:"subsDays", input:"{{item.rate.subsDays}}", output:0, example:" ", status:false, module:"order.rentalOrderItems"},
	{name:"subsDaysFlag", input:"{{item.rate.subsDaysFlag}}", output:"true/false", example:"", status:false, module:"order.rentalOrderItems"},
	{name:"weekend", input:"{{item.rate.weekend}}", output:0, example:"", status:false, module:"order.rentalOrderItems"},
	{name:"weekendFlag", input:"{{item.rate.weekendFlag}}", output:"true/false", example:"", status:false, module:"order.rentalOrderItems"},

	/* invoice */
	
	{name:"accountEmail", input:"{{invoice.accountEmail}}", output:"hello@insphire.com", example:"Return invoice account email", status:false,  module:"invoice"},
	{name:"accountName", input:"{{invoice.accountName}}", output:"inspHire Ltd", example:"Return invoice account name ", status:false, module:"invoice"},
    {name:"applyCustomerTaxType", input:"{{invoice.applyCustomerTaxType}}", output:"1", example:"", status:false, module:"invoice"},
	{name:"billingAddressString", input:"{{invoice.billingAddressString}}", output:"inspHire Ltd, Unit 5, Chase Park, Daleside Road, Nottingham, Nottinghamshire, United Kingdom, NG2 4GT", example:"Return invoice full billing address", status:false, module:"invoice"},
	{name:"billingPlaceName", input:"{{invoice.billingPlaceName}}", output:"inspHire Ltd", example:"Return invoice billing place name ", status:false, module:"invoice"},
	{name:"createDate", input:"{{invoice.createDate}}", output:"2023-12-13T14:58:16.296297Z", example:"Return invoice create date ", status:false,  module:"invoice"},
	{name:"currencySymbol", input:"{{invoice.currencySymbol}}", output:"£", example:"Return invoice currency symbol ", status:false,  module:"invoice"},
	{name:"customerReference", input:"{{invoice.customerReference}}", output:"Customer Ref: 1234", example:"Return invoice customer ref  ", status:false,  module:"invoice"},
	{name:"deliveryAddressString", input:"{{invoice.deliveryAddressString}}", output:"99,  Street, Nottingham, England, United Kingdom, NG9 9FD", example:"Return invoice full delivery address ", status:false,  module:"invoice"},
	{name:"deliveryPlaceName", input:"{{invoice.deliveryPlaceName}}", output:"House", example:"Return invoice delivery place name ", status:false,  module:"invoice"},
	{name:"depotName", input:"{{invoice.depotName}}", output:"Alan Store", example:"Return invoice depot name ", status:false, module:"invoice"},
	{name:"documentNumber", input:"{{invoice.documentNumber}}", output:"12 - ORD:GB/ALA", example:"Return invoice doc number ", status:false,  module:"invoice"},
	{name:"dueDate", input:"{{invoice.dueDate}}", output:"1753-01-01T00:00:00Z", example:"Return invoice due date ", status:false,  module:"invoice"},
    {name:"emailTo", input:"{{invoice.emailTo}}", output:"", example:"Return email invoice has been sent to ", status:false,  module:"invoice"},
    {name:"exchangeRate", input:"{{invoice.exchangeRate}}", output:"1", example:"Return invoice exchange rate ", status:false,  module:"invoice"},
    {name:"hasBeenEmailedFlag", input:"{{invoice.hasBeenEmailedFlag}}", output:"true/false", example:"Return whether or not the invoice has been emailed ", status:false,  module:"invoice"},
	{name:"invoiceDate", input:"{{invoice.invoiceDate}}", output:"2023-12-13T14:45:00Z", example:"Return invoice date ", status:false,  module:"invoice"},
	{name:"noOfItems", input:"{{invoice.noOfItems}}", output:"1h", example:"Return number of items in the invoice ", status:false,  module:"invoice"},
    {name:"orderName", input:"{{invoice.orderName}}", output:"12 - ORD:GB/ALA", example:"Return order name", status:false,  module:"invoice"},
    {name:"orderedBy", input:"{{invoice.orderedBy}}", output:"John Cash", example:"Return who ordered the order", status:false,  module:"invoice"},
	{name:"ownerUserEmail", input:"{{invoice.ownerUserEmail}}", output:"alan.da.silva.souza@current-rms.com", example:"Return invoice owner email ", status:false,  module:"invoice"},
	{name:"ownerUserFullName", input:"{{invoice.ownerUserFullName}}", output:"Alan Souza", example:"Return invoice owner name ", status:false,  module:"invoice"},
	{name:"paymentTermName", input:"{{invoice.paymentTermName}}", output:"30 Days", example:"Return invoice payment term ", status:false,  module:"invoice"},
	{name:"salesPerson", input:"{{invoice.salesPerson}}", output:"Will Smith", example:"Return invoice sales person ", status:false,  module:"invoice"},
	{name:"status", input:"{{invoice.status}}", output:"Active", example:"Return invoice status ", status:false,  module:"invoice"},
	{name:"timeZone", input:"{{invoice.timeZone}}", output:"Europe/London", example:"Return invoice time zone ", status:false,  module:"invoice"},
	{name:"timeZoneName", input:"{{invoice.timeZoneName}}", output:"(+00:00) Europe/London", example:"Return invoice time zone name ", status:false,  module:"invoice"},
	{name:"totalCharge", input:"{{invoice.totalCharge}}", output:20, example:"Return invoice total charge without tax", status:false, module:"invoice"},
	{name:"totalChargeIncludingTax", input:"{{invoice.totalChargeIncludingTax}}", output:24, example:"Return invoice total charge inc tax ", status:false,  module:"invoice"},
	{name:"totalInvoiced", input:"{{invoice.totalInvoiced}}", output:12, example:"Return invoice total invoiced ", status:false,  module:"invoice"},
	{name:"totalRental", input:"{{invoice.totalRental}}", output:20, example:"Return invoice  total rental", status:false,  module:"invoice"},
	{name:"totalSale", input:"{{invoice.totalSale}}", output:0, example:"Return invoice total sale ", status:false,  module:"invoice"},
	{name:"totalService", input:"{{invoice.totalService}}", output:0, example:"Return invoice total service ", status:false,  module:"invoice"},
    {name:"totalPayment", input:"{{invoice.totalPayment}}", output:20, example:"Return invoice total payment", status:false, module:"invoice"},
    {name:"totalPaymentOutstanding", input:"{{invoice.totalPaymentOutstanding}}", output:20, example:"Return invoice total payment outstanding", status:false, module:"invoice"},
    {name:"type", input:"{{invoice.type}}", output:20, example:"Return document type", status:false, module:"invoice"},
	{name:"totalTax", input:"{{invoice.totalTax}}", output:4, example:"Return invoice total tax ", status:false,  module:"invoice"},
	{name:"totalWeight", input:"{{invoice.totalWeight}}", output:30, example:"Return invoice total weight ", status:false,  module:"invoice"},
	{name:"weightUnitSymbol", input:"{{invoice.weightUnitSymbol}}", output:"kg", example:"Return invoice total weight unit ", status:false, module:"invoice"},

	/* invoice.billingPlace */
	
	{name:"address1", input:"{{invoice.billingPlace.address1}}", output:"inspHire Ltd", example:"Return invoice billing place address", status:false, module:"invoiceBillingPlace" },
	{name:"address2", input:"{{invoice.billingPlace.address2}}", output:"Unit 5, Chase Park, Daleside Road", example:"Return invoice billing place address", status:false, module:"invoiceBillingPlace"  },
	{name:"city", input:"{{invoice.billingPlace.city}}", output:"Nottingham", example:"Return invoice billing place city", status:false, module:"invoiceBillingPlace"  },
	{name:"countryIso", input:"{{invoice.billingPlace.countryIso}}", output:"GB", example:"Return invoice billing place country symbol", status:false, module:"invoiceBillingPlace"  },
	{name:"countryName", input:"{{invoice.billingPlace.countryName}}", output:"United Kingdom", example:"Return invoice billing place name", status:false, module:"invoiceBillingPlace"  },
	{name:"county", input:"{{invoice.billingPlace.county}}", output:"Nottinghamshire", example:"Return invoice billing place county", status:false, module:"invoiceBillingPlace"  },
	{name:"email", input:"{{invoice.billingPlace.email}}", output:"hello@insphire.com", example:"Return invoice billing place email", status:false, module: "invoiceBillingPlace" },
	{name:"fax", input:"{{invoice.billingPlace.fax}}", output:"example.com", example:"Return invoice billing place fax", status:false, module:"invoiceBillingPlace" },
	{name:"name", input:"{{invoice.billingPlace.name}}", output:"inspHire Ltd", example:"Return invoice billing place name", status:false, module: "invoiceBillingPlace" },
	{name:"postcode", input:"{{invoice.billingPlace.postcode}}", output:"NG2 4GT", example:"Return invoice billing place postcode", status:false, module:"invoiceBillingPlace"  },
	{name:"telephone", input:"{{invoice.billingPlace.telephone}}", output:"0115 979 3377", example:"Return invoice billing place telephone", status:false, module: "invoiceBillingPlace" },
	{name:"type", input:"{{invoice.billingPlace.type}}", output:"Head Office", example:"Return invoice billing place type", status:false, module:"invoiceBillingPlace"  },
	{name:"website", input:"{{invoice.billingPlace.website}}", output:"www.inspHire.com", example:"Return invoice billing place website", status:false, module:"invoiceBillingPlace"  },

	
	/*  invoice.deliveryAddress */

	{name:"address1", input:"{{invoice.deliveryAddress.address1}}", output:"99, Brightmoor Street", example:"Return invoice delivery address ", status:false, module: "invoiceDeliveryAddress"},
	{name:"address2", input:"{{invoice.deliveryAddress.address2}}", output:"", example:"Return invoice delivery address ", status:false, module: "invoiceDeliveryAddress"},
	{name:"city", input:"{{invoice.deliveryAddress.city}}", output:"Nottingham", example:"Return invoice delivery address city", status:false, module: "invoiceDeliveryAddress"},
	{name:"countryIso", input:"{{invoice.deliveryAddress.countryIso}}", output:"GB", example:"Return invoice delivery address country initials", status:false, module: "invoiceDeliveryAddress"},
	{name:"countryName", input:"{{invoice.deliveryAddress.countryName}}", output:"United Kingdom", example:"Return invoice delivery address country", status:false, module: "invoiceDeliveryAddress"},
	{name:"county", input:"{{invoice.deliveryAddress.county}}", output:"England", example:"Return invoice delivery address county ", status:false, module:"invoiceDeliveryAddress" },
	{name:"postcode", input:"{{invoice.deliveryAddress.postcode}}", output:"NG9 9FD", example:"Return invoice delivery address postcode ", status:false, module:"invoiceDeliveryAddress" },

    /* invoice.paymentTerm  */

    {name:"code", input:"{{invoice.paymentTerm.code}}", output:30, example:"Return invoice payment term code", status:false, module:"invoice.PaymentTerm"},
    {name:"days", input:"{{invoice.paymentTerm.days}}", output:30, example:"Return invoice payment term days", status:false, module:"invoice.PaymentTerm"},
    {name:"description", input:"{{invoice.paymentTerm.description}}", output:"30 Days From Invoice Date", example:"Return invoice payment term description", status:false, module:"invoice.PaymentTerm"},
    {name:"name", input:"{{invoice.paymentTerm.name}}", output:"30 Days", example:"Return invoice payment term name", status:false, module:"invoice.PaymentTerm"},
    {name:"periodType", input:"{{invoice.paymentTerm.periodType}}", output:"Invoice Date", example:"Return invoice payment term period type", status:false, module:"invoice.PaymentTerm"},




	/* LOOP invoice.rentalinvoiceItems */

	
	{name:"chargingEndDate", input:"{{item.chargingEndDate}}", output:"2023-12-17T17:00:00Z", example:"Return item charge end date", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"chargingStartDate", input:"{{item.chargingStartDate}}", output:"2023-12-14T09:36:00Z", example:"Return item charge start date", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"currencySymbol", input:"{{item.currencySymbol}}", output:"£", example:"Return item currency symbol", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"description", input:"{{item.description}}", output:"note description", example:"Return item note description", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"discount", input:"{{item.discount}}", output:0, example:"Return item discount", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"discountableFlag", input:"{{item.discountableFlag}}", output:"true/false", example:"Return whether or not the item has a discount", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"id", input:"{{item.id}}", output:"16d43ce0-2153-4aa0-92d7-051521cf4d95", example:"Return the item id", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"index", input:"{{item.index}}", output:0, example:"Return item index position in the array", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"itemName", input:"{{item.itemName}}", output:"6\" Bucket", example:"Return item name", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"level", input:"{{item.level}}", output:0, example:"Return item level - accessory 1 and subsequently ", status:false, module:"invoice.rentalinvoiceItems"},
    {name:"manualInvoiceFlag", input:"{{item.manualInvoiceFlag}}", output:"true/false", example:"Return whether or not the invoice has been manually raised ", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"minimumHirePeriodAppliedFlag", input:"{{item.minimumHirePeriodAppliedFlag}}", output:"true/false", example:"Return whether or not the item has a minimum rental period", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"price", input:"{{item.price}}", output:10, example:"Return item price", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"quantity", input:"{{item.quantity}}", output:1, example:"Return item quantity", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"rateDefinitionLeadingRateType", input:"{{item.rateDefinitionLeadingRateType}}", output:0, example:"", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"rateDefinitionName", input:"{{item.rateDefinitionName}}", output:"Daily Rate", example:"Return item rate name", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"rateDefinitionRateType", input:"{{item.rateDefinitionRateType}}", output:0, example:"Return item rate type ", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"revenueGroupName", input:"{{item.revenueGroupName}}", output:"Rental Revenue", example:"Return item revenue group ", status:false, module:"invoice.rentalinvoiceItems"},
    {name:"stockMethod", input:"{{item.stockMethod}}", output:1, example:"Return item stock method", status:false, module:"invoice.rentalinvoiceItems"},
    {name:"stockType", input:"{{item.stockType}}", output:1, example:"Return item stock type", status:false, module:"invoice.rentalinvoiceItems"},
    {name:"subsequentChargeFlag", input:"{{item.subsequentChargeFlag}}", output:"true/false", example:"", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"stockLevelItemNumber", input:"{{item.stockLevelItemNumber}}", output:"BUCK001", example:"Return item stock number ", status:false, module:"invoice.rentalinvoiceItems"},
    {name:"surchargeRate", input:"{{item.surchargeRate}}", output:0, example:"Return item surcharge rate", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"taxClassName", input:"{{item.taxClassName}}", output:"Standard VAT", example:"Return item tax class name", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"thumbLink", input:"{{item.thumbLink}}", output:"https://europa-dev.s3.eu-west-1.amazonaws.com/image", example:"Return item image", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"totalCharge", input:"{{item.totalCharge}}", output:20, example:"Return item total charge", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"totalDays", input:"{{item.totalDays}}", output:2, example:"Return item total days on invoice", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"totalMonths", input:"{{item.totalMonths}}", output:1, example:"Return item total months", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"totalTax", input:"{{item.totalTax}}", output:4, example:"Return item total tax", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"totalWeekends", input:"{{item.totalWeekends}}", output:1, example:"Return item total weekends", status:false, module:"invoice.rentalinvoiceItems"},
	{name:"totalWeeks", input:"{{item.totalWeeks}}", output:1, example:"Return item total weeks", status:false, module:"invoice.rentalinvoiceItems"},
	
]




export const list = [
    {name:"Order", value: "order"}, 
    {name:"Order Billing Place", value: "orderBillingPlace"}, 
    {name:"Order Collection Address", value: "orderCollectionAddress"}, 
    {name:"Order Collection Place", value: "orderCollectionPlace"}, 
    {name:"Order Delivery Address", value: "orderDeliveryAddress"}, 
    {name:"Order Delivery Place", value: "orderDeliveryPlace"},
	{name:"Order Items", value:"order.rentalOrderItems" },
	{name:"Invoice", value:"invoice"},
	{name:"Invoice Billing Place" , value:"invoiceBillingPlace"},
	{name:"Invoice Delivery Address" , value:"invoiceDeliveryAddress"},
	{name:"Invoice Payment Term" , value:"invoice.PaymentTerm"},
	{name:"Invoice Items" , value:"invoice.rentalinvoiceItems"},

]
